
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  namespace: 
  labels:
    app: boardgame-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: boardgame-app
  template:
    metadata:
      labels:
        app: boardgame-app
    spec:
      containers:
        - name: boardgame-container
          image: sanketmule/boardgame:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          
        

