apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  namespace: boardgame-web-app-ns
spec:
  type: LoadBalancer
  selector:
    app: boardgame-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

